### ISSUE TITLE
Finalize validator dashboard: filters, search, pagination, timestamps

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#335] opened 2020-08-07 05:52 UTC
### User Story
As a validator I would like my dashboard to have filters, search and pagination

> #### Acceptance criteria
> 
> ```
> Given << some context >>
> When << some action is carried out>>
> Then << a set of observable outcomes should occur >>
> ```
> 

## Tasks:
- [ ] Add filters, search and pagination: https://www.figma.com/file/6mW06zt7214LgwZIoY2VVF/Requester-signupflow%3A-Project-%F0%9F%92%AF?node-id=0%3A1

- [ ] Add timestamps: https://www.figma.com/file/cHEYJrdU5hGz76pZNgsDkP/Adding-more-explicit-dates-to-validation-process?node-id=1%3A3306

**Comment by jamalv** [comment] 2020-08-07 05:52
Validator dashboard still needs pagination, search and filters

**Comment by maxvisser** [comment] 2020-08-07 07:14
duplicate of https://github.com/teamforus/general/issues/325

**Comment by maxvisser** [comment] 2020-08-07 07:14
Maybe make this one specific for validator dashboard

**Comment by maxvisser** [comment] 2020-08-10 15:03
If the scope is just pagination, search and filters. This does not need to be that big. I see the scope as Medium.

**Comment by maxvisser** [comment] 2020-08-10 15:03
Needs an improvement proposal (what needs to be changed)

**Comment by jamalv** [comment] 2020-08-11 06:41
@maxvisser added two figma proposals, they can be reviewed on design and text and then be planned in

**Comment by maxvisser** [comment] 2020-08-12 09:02
Duplicate of https://github.com/teamforus/general/issues/319

**Closed** 2020-08-12 09:02 UTC
Labels: Approval: Granted, Epic, Phase 2: Design, Priority: Must have, Scope: Medium, Status: Planned, Type: Epic, project-100
