### ISSUE TITLE
CR: Providers/Actions sort options

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#533] opened 2020-10-12 15:00 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
- As a user I would like to sort the actions/providers by price low-high high-low, alphabetical order a-z z-a

**Comment by maxvisser** [comment] 2020-10-13 07:16
Duplicate of #479

**Closed by maxvisser** 2020-10-13 07:16 UTC
Labels: Approval: Not requested, Status: Not Planned, Type: Change request, project-100
