### ISSUE TITLE
Requester signupflow; skip first image step

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#365] opened 2020-08-17 20:36 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Jamal

### Change description
Remove this step:
<img width="1138" alt="Screenshot 2020-08-17 at 22 34 50" src="https://user-images.githubusercontent.com/30194799/90441855-f0c21e00-e0d9-11ea-90ea-70f409aa4598.png">

And go straight to this step:
<img width="1344" alt="Screenshot 2020-08-17 at 22 35 40" src="https://user-images.githubusercontent.com/30194799/90441875-fe77a380-e0d9-11ea-8c8c-94530c64c26a.png">

Note: please remove the text: Er wordt gekeken of u al aan voorwaarden voldoet, en u kan tussentijds afbreken en op een ander moment verder gaan.

**Comment by maxvisser** [comment] 2020-08-25 20:17
Seems to be a duplicate of #345

**Comment by maxvisser** [comment] 2020-08-28 13:18
Could you check #345 and decide what to do? @jamalv

**Comment by maxvisser** [comment] 2020-10-19 08:17
released

**Closed by maxvisser** 2020-10-19 08:17 UTC
Labels: Approval: Not requested, Scope: Small, Status: Not Planned, Type: Change request, project-31
