### ISSUE TITLE
CR: CR: Download upload voorbeeld add product-id dropdown

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#303] opened 2020-07-22 08:47 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor Nijmegen Implementation Maarten ITSM Max

### Change description
- As a Sponsor I would like to be able to select the product-id from the dropdown in de Excell sheet instead of asking for it.

**Comment by maxvisser** [comment] 2020-07-22 09:16
Duplicate of https://github.com/teamforus/general/issues/297

**Closed by maxvisser** 2020-07-22 09:16 UTC
Labels: Approval: Not requested, Status: Not Planned, Type: Change request
