### ISSUE TITLE
Adding more explicit dates to validation process

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#329] opened 2020-08-05 08:21 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Validators

### Change description
As a validator I would like to clearly see the dates of certain actions so that I know if I'm responding within the appropriate timeframe.

figma: https://www.figma.com/file/cHEYJrdU5hGz76pZNgsDkP/Adding-more-explicit-dates-to-validation-process?node-id=0%3A1

**Comment by maxvisser** [comment] 2020-08-05 08:51
Which dates?

fund request creation date?

**Comment by jamalv** [comment] 2020-08-05 09:01
Yes, I think that is the most important one, but also for the messages I think.

**Comment by maartenfv** [comment] 2020-08-05 12:56
@jamalv I agree. Every message needs a date and time.

**Comment by maxvisser** [comment] 2020-08-07 07:28
Made an initial scope estimation. added project-100 label

**Comment by maxvisser** [comment] 2020-09-21 13:30
Seems to be a duplicate of https://github.com/teamforus/general/issues/319

**Closed by maxvisser** 2020-09-21 13:30 UTC
Labels: Approval: Not requested, Priority: Should have, Scope: Small, Status: Not Planned, Type: Change request, project-100, project-31
