### ISSUE TITLE
CR: Product Image Checkbox 

### ISSUE THREAD

**Issue by SjoerdHilhorst** [teamforus/general#534] opened 2020-10-12 15:12 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen
Note: This change was requested after acceptance testing with stakeholders of project 100

### Change description
- Adding a product: Add a checkbox next to picture upload area that says that you have the rights to the image

**Comment by maxvisser** [comment] 2020-10-13 07:00
duplicate of https://github.com/teamforus/general/issues/509

**Closed by maxvisser** 2020-10-13 07:00 UTC
Labels: Approval: Not requested, Status: Not Planned, Type: Change request, project-100
