### ISSUE TITLE
IP: Activate with DigiD instead of activation code

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#377] opened 2020-08-21 11:46 UTC
## Context
For multiple upcoming projects we need to be able to activate vouchers using DigiD. 

The prevalidations will be added by CSV file. The BSN numbers will be in the CSV file.

## User stories
As a requester I want my vouchers to be automatically added to my account if I have the required prevalidations. If I **don't** have the right prevalidations linked to my BSN number, I would like to be redirected to the signupflow.

**Comment by maxvisser** [comment] 2020-08-25 19:14
probably a duplicate of #359 #85 #266

**Comment by maxvisser** [comment] 2020-09-17 12:53
I will close this one in favor of #359

**Closed by maxvisser** 2020-09-17 12:53 UTC
Labels: Priority: Must have, Scope: Big
