### ISSUE TITLE
Assign voucher with BSN to identity which logges in with DigiD 

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#300] opened 2020-07-21 15:38 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Client

### Change description
As a sponsor I would like to give out a voucher trough the voucher generator, and to allow a requester to apply to the same fund and automatically receive the voucher in their account.

**Sponsor workflow example:**
* Sponsor assigns (product/budget) vouchers (on bsn: #299) using the voucher generator (todo: check this userflow)
* A requester receives the voucher /(activates?)
* A requestor goes to the fund signup flow and requests the voucher again
  * requestor gets redirected to their existing voucher :)

## Goal
A user that has received a voucher using the voucher generator, should not be able to also request a voucher with DigiD. 

## Proposal
Save BSNs & Email adresses that have recieved a voucher with the voucher generator for this fund, and when somebody later applies with DigiD, don't give out the voucher. The list with BSN numbers could be provided in any format.

**Comment by maxvisser** [comment] 2020-07-21 17:09
Fixed the title. As the only reason this is possible as a non assigned voucher has no correlation to the UID from the requester (voucher is not yet owned by anyone)

**Comment by jamalv** [comment] 2020-07-22 09:46
labeling this could have until the related project becomes "official" then it will become must-have :)

**Comment by maxvisser** [comment] 2020-07-29 10:48
probably duplicate of https://github.com/teamforus/general/issues/85

**Comment by jamalv** [comment] 2020-09-09 14:50
Even better would be to just add it to your account

**Comment by maxvisser** [comment] 2020-10-19 08:15
released

**Closed by maxvisser** 2020-10-19 08:15 UTC
Labels: Approval: Not requested, Priority: Must have, Scope: Medium, Status: Not Planned, Type: Change request, project-139
