### ISSUE TITLE
Webshop activation modal: input field creates double numbers NUMPAD

### ISSUE THREAD

**Issue by demylubbers** [teamforus/general#404] opened 2020-09-04 12:05 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Demy Lubbers

### Change description
- If I want to enter my activation code using the numbers on the right side of the keyboard. They get filled in with dubbel the digits. Example: Activation code is 1814. Becomes -> 11881144.

**Comment by maxvisser** [comment] 2020-09-07 06:42
Need priority and project label before it can be planned.

**Comment by maxvisser** [comment] 2020-12-01 08:27
Can't reproduce the issue will close it

**Closed by maxvisser** 2020-12-01 08:27 UTC
Labels: Approval: Requested, Scope: Small, Status: Not Planned, Type: Change request
