### ISSUE TITLE
Vouchers should indicate year of start date fund.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#673] opened 2020-12-22 15:48 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Maarten

### Change description

As a user I would like not to be confused. Can we add years? Can we archieve and remove vouchers?

![image](https://user-images.githubusercontent.com/30211022/102906723-54d46480-4475-11eb-8198-89d41703dbf7.png)

![image](https://user-images.githubusercontent.com/10818702/106434203-81669d80-6471-11eb-903c-58467fde25a2.png)

**Comment by maxvisser** [comment] 2020-12-30 08:29
duplicate of #108

**Comment by maxvisser** [comment] 2020-12-30 08:30
As you also mentioned year. I will change this into specifically that CR.

**Comment by maxvisser** [comment] 2021-02-01 08:39
This morning I also got a bit confused as I worked on a CR. If a voucher is expired you cant really see on which date is has expired on the webshop. So you currently dont know which year the voucher is from. This seem pretty impactfull.

**Comment by jamalv** [comment] 2021-02-01 12:59
Needs figma proposal: should show expiration date of the voucher in both the me app and the webshop, as long as you can see that the voucher is expired, and see the dates when you open the details view.

Should be tested on iOS, seems not to be a problem on android (anymore)

**Closed** 2021-04-19 05:25 UTC
Labels: Impact: Extensive, Scope: Medium, Urgency: Medium
