### ISSUE TITLE
No price product displays in webshop that its free; while it should show no price.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#524] opened 2020-10-12 08:53 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Groningen

**Note:** This change was requested after acceptance testing with stakeholders of project 100
**Requirement:** D1

### Change description
- We got feedback from Groningen that adding a product that you only want to use for discount is really confusing. I also think it's confusing, I don't even understands how it works. 

From what I understand:
1. Provider fils form to add product
2. Provider check the checkbox: "Geen prijs" (why not: Gratis)
3. Provider adds in the title that it's only for discount?
4. Product is getting added to the webshop and it tells the user it's free, but the title says it's only about a discount. Bit confusing. (we could just remove the Free tag on the webshop if someone wants to add a discount)

How does the provider know they can do it like this? UX is not clear enough to guess you should use it this way.

**Comment by maxvisser** [comment] 2020-10-12 17:20
Yes this is possible using workaround described in your userflow; Sponsor should actively communicate this (A discount is a offer without a price). Not sure what they expect (how this should work)

**Comment by SjoerdHilhorst** [comment] 2020-10-13 08:49
https://github.com/teamforus/implementation/issues/531

**Comment by maxvisser** [comment] 2020-10-13 09:08
Can't really scope as for me its not clear what the change is that is proposed.

**Comment by jamalv** [comment] 2020-10-15 08:49
If this is not already the case (should be tested), this should be done at least:
- [ ] If "geen prijs" is checked, the "free" label should be removed for this offer in the webshop

This is also why it is not marked as "free" in the provider settings, because a provider can add a discount this way; "25% discount on all haircuts for men", for example. UX needs improvements indeed.

**Comment by jamalv** [comment] 2020-10-15 08:55
@maxvisser could you please plan that task in? I think scope small?

**Comment by maxvisser** [comment] 2020-10-15 09:18
And what if it is actually free?

**Comment by maxvisser** [comment] 2020-10-15 09:19
Scope is aswell for the Me-app applicalble; List and confirmation currently will show 'gratis'

**Comment by maxvisser** [comment] 2020-10-15 09:21
Discussed this one aswell with Gerben, he said the problem is not really that the webshops says gratis or €0 euro's; just that the mindset of the provider is not that they would add a discount the way we implemented it @GerbenBosschieter Could you confirm this?

**Comment by maartenfv** [comment] 2020-11-13 14:29
This one is a big problem. The user flow needs to be discussed with more people checked.

**Comment by maartenfv** [comment] 2020-11-13 15:33
![image](https://user-images.githubusercontent.com/30211022/99089774-04dcc500-25ce-11eb-9de2-b53200a55567.png)

**Comment by maartenfv** [comment] 2020-11-13 15:34
This issue and the comments of Groningen are bout the whole flow. Not just the info thing and the "Geen prijs button"

**Comment by jamalv** [comment] 2020-11-18 13:35
New subtask: https://www.figma.com/file/siGNnFJekZbRAlTVQp2rai/Show-discount-on-cards?node-id=1%3A8893

**Closed** 2020-12-01 07:56 UTC
Labels: Approval: Granted, Epic, Priority: Must have, Scope: Small, Status: Planned, Status: Question, Type: Change request, project-100
