### ISSUE TITLE
Search providers

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#321] opened 2020-08-02 11:50 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
As a requester I want to search based on provider name

https://www.figma.com/file/8OFRwEqgCfACjtEYh74y9Y/Search-providers?node-id=11%3A2407

**Comment by maxvisser** [comment] 2020-08-03 07:23
Duplicate of https://github.com/teamforus/general/issues/181

**Closed by maxvisser** 2020-08-03 07:23 UTC
Labels: Approval: Not requested, Priority: Could have, Status: Not Planned, Type: Change request
