### ISSUE TITLE
Acties page on webshop should have titles 'Aanbod'

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#676] opened 2020-12-23 10:13 UTC
@maxvisser commented on [Thu Sep 10 2020](https://github.com/teamforus/forus/issues/1758)

## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/92572579-ea603580-f284-11ea-9652-b6aad83e4fdf.png)

---

@maxvisser commented on [Mon Sep 21 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-696098909)

Fixed

---

@maxvisser commented on [Wed Nov 25 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-733783579)

@SjoerdHilhorst I see you changed the page subsidies to 'Aanbod' and the navbar item to 'Aanbod'; seems that this was not in the text fix issue as a planned task. Could you revert these changes?

---

@SjoerdHilhorst commented on [Mon Nov 30 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-735639951)

This mentions changing it to "aanbod":
https://docs.google.com/spreadsheets/d/1B1rSQjzejkIMThG2bAIW27Xg6Ol2GLY-hLts7b5vcsI/edit#gid=433994186&range=C26

@jamalv what do you think

---

@maxvisser commented on [Mon Nov 30 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-735670355)

We already reversed the change in release 0.16.3

---

@maxvisser commented on [Mon Nov 30 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-735670565)

Did you implement any other textual fixes from the spreadsheet? 

---

@maartenfv commented on [Tue Dec 22 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-749616268)

@jamalv Can we change it to aanbod? As requested by Groningen?

---

@maxvisser commented on [Wed Dec 23 2020](https://github.com/teamforus/forus/issues/1758#issuecomment-750081915)

Please open a new CR instead of opening old forus tasks.

**Comment by maxvisser** [comment] 2020-12-23 10:14
@maartenfv copied this one over for you 👍

**Comment by jamalv** [comment] 2021-01-06 20:00
this is a duplicate of: https://github.com/teamforus/general/issues/677

**Closed by jamalv** 2021-01-06 20:00 UTC
Labels: Impact: Significant, Priority: Must have, Urgency: Medium - Next 3 sprints, project-100
