### ISSUE TITLE
Webshop: the link "aanmelden als aanbieder" goes directly to third step

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#599] opened 2020-11-26 17:14 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

![Aanmelden als aanbieder beter](https://user-images.githubusercontent.com/30211022/100378442-64e25b00-3013-11eb-80b3-11e5268ee86a.JPG)

Cleared my cache still have bug that the aanmelden als aanbieder link goes directly to this page. 
![image](https://user-images.githubusercontent.com/30211022/100378338-35335300-3013-11eb-80d2-02d6f31618be.png)

### Requested by:
-

### Change description
-

**Comment by maxvisser** [comment] 2020-11-27 08:13
Hi Maarten, I tried reproducing this issue; But I can't. We do store the step you were on when you closed the browser.

![image](https://user-images.githubusercontent.com/10818702/100426081-9f3e0d80-3090-11eb-9cab-81444a1c28ea.png)

So could you maybe aswell check what number you find in your local storage?

- Right click, inspect element
- Select tab in DevTools with the name 'Application' / 'Applicatie'
- Select Local Storage 
- Select url of Forus.io

**Comment by maxvisser** [comment] 2020-11-27 08:14
We store this state so you can continue where you left even if you return back from your mail to the signupflow.

**Comment by maartenfv** [comment] 2020-12-09 15:01
![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/edd03886-581e-4f77-bf40-dab0b5e68906)

**Comment by jamalv** [comment] 2020-12-11 09:42
Solution here would be to add a back button I think.

**Comment by maartenfv** [comment] 2020-12-16 13:26
@maxvisser Do we have an update?

**Comment by maxvisser** [comment] 2020-12-17 12:15
Not what your issue is. I can't reproduce it.

**Comment by jamalv** [comment] 2020-12-18 13:42
Issue is that when you go to https://forus.io/provider/sign-up and you click next two times, there is no way to go back to the previous page, which is frustrating if you want to read a bit more info that you might have missed.

Proposed solution is to add a back button.

![Screenshot 2020-12-18 at 14.39.21.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/9afa8fbc-bede-4950-bdb6-84805c801d04)

@danrminds could you create a task (or check if there already is one) for adding the back button to this page:

![Screenshot 2020-12-18 at 14.42.16.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/78757f84-2ef8-4f4b-8e0f-276b6dd29a4d)

**Comment by maxvisser** [comment] 2020-12-18 14:01
No thats this issue https://github.com/teamforus/general/issues/629. Maarten is saying he goes directly to the SMS page from the webshop

**Comment by jamalv** [comment] 2020-12-21 08:03
They are strongly related though, if maarten would open a private tab, he would be able to go to this page, but since the position is stored somewhere in the browser (clearing cache doesn't help) you don't have a possibility to go (back) to the first to info pages and go directly to the sms page if you go to forus.io/provider/sign-up

**Comment by maxvisser** [comment] 2020-12-21 09:12
If thats the fix for  this issue; lets close on or the other ;)

**Comment by jamalv** [comment] 2020-12-21 13:08
will be fixed by: https://github.com/teamforus/general/issues/629, progress can be tracked there

**Closed by jamalv** 2020-12-21 13:08 UTC
Labels: Approval: Not requested, Priority: Must have, Status: Not Planned, Type: Change request
