### ISSUE TITLE
Mobile friendly dashboards

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/general#255] opened 2020-06-29 19:02 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Smartphones 📱 
### Change description
- As a smartphone I would like to display the dashboards propperly.

Since we have the new signup flow almost done. We should also work on the dashboards to make it mobile friendly for better UX. I think we underestimate what the current State of the dashboard is 👀 

![image](https://user-images.githubusercontent.com/38419514/86045333-ba5a1200-ba4b-11ea-9813-f618f6a2faae.png)

![image](https://user-images.githubusercontent.com/38419514/86045345-bf1ec600-ba4b-11ea-9727-7a15854f1c92.png)
![image](https://user-images.githubusercontent.com/38419514/86045366-c645d400-ba4b-11ea-97e1-9ae88b03b0db.png)

![image](https://user-images.githubusercontent.com/38419514/86045385-cba31e80-ba4b-11ea-8cc7-aa9aab61444a.png)

**Comment by maxvisser** [comment] 2020-07-01 14:24
would propose to go through the dashboard; and hide alot of funtionality and start with a small mobile friendly scope. Iterate until all pages are mobile friendly.

**Comment by maxvisser** [comment] 2020-07-01 14:29
also we could check if people use this mess before removing alot of functionality (hiding it)

**Comment by maxvisser** [comment] 2020-08-12 07:34
Duplicate of #255 As 255 is older I will close this one.

**Closed** 2020-08-12 07:35 UTC
Labels: Approval: Granted, Phase 1: Define, Priority: Could have, Status: Not Planned, Type: Change request
