### ISSUE TITLE
CR: Add Column with unique id number or (klantnummer or BSN) to voucher generator screens.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#301] opened 2020-07-22 08:20 UTC
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
- Sponsor Nijmegen.

### Change description
- As a sponsor, I want to be able to add a unique ID number to the CSV upload when generating QR-codes.
- As a sponsor, **I do not** want to use the "note" field to keep track of whom I have given a code or to write down BSN or customer number.
- As a sponsor, I want to be able to search through these new numbers.

*Note* The voucher generators are going to be used to generate thousands of codes. This means that it will not just be a feature for edge cases. The design needs to take into account these demands in terms of search-ability etc.

For the busregeling this is a must-do issue.

![image.png](https://images.zenhubusercontent.com/5e79d94fc5b97af9090e495c/460fd94a-9480-4140-b98e-94201bfa50e3)

**Comment by maxvisser** [comment] 2020-07-22 09:40
If you also include assigning to this issue we could close this one; as this one has more content;
https://github.com/teamforus/general/issues/298

**Comment by maxvisser** [comment] 2020-07-27 11:42
Duplicate of https://github.com/teamforus/general/issues/298

**Closed by maxvisser** 2020-07-27 11:42 UTC
Labels: Approval: Not requested, Status: Not Planned, Type: Change request
